export const MESSAGE_TYPES = ["TEXT", "IMAGE", "VIDEO", "FILE", "SYSTEM"] as const;

export const ROOM_ROLES = ["OWNER", "ADMIN", "MEMBER"] as const;

export const PLUGIN_STATES = ["INACTIVE", "RUNNING", "ERROR"] as const;

export const EMAIL_VERIFICATION_TYPES = ["REGISTER", "RESET_PASSWORD"] as const;

export const DEFAULTS = {
  ROOM_MAX_MEMBERS: 50,
  ROOM_LIST_PAGE_SIZE: 20,
  MESSAGE_PAGE_SIZE: 50,
  VERIFICATION_CODE_LENGTH: 6,
  VERIFICATION_CODE_EXPIRY_MINUTES: 10,
  VERIFICATION_MAX_ATTEMPTS: 5,
  INVITATION_EXPIRY_HOURS: 24,
  ACCESS_TOKEN_EXPIRY_MINUTES: 15,
  REFRESH_TOKEN_EXPIRY_DAYS: 7,
  BCRYPT_SALT_ROUNDS: 12,
  MAX_MESSAGE_LENGTH: 5000,
  MAX_ROOM_NAME_LENGTH: 50,
  MIN_ROOM_MEMBERS: 2,
  MAX_ROOM_MEMBERS: 100,
} as const;

export const FEATURE_FLAGS = {
  ENABLE_MEDIA_MESSAGES: process.env.ENABLE_MEDIA_MESSAGES === "true",
} as const;